// <auto-generated />
using System;
using Financials.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Financials.Migrations
{
    [DbContext(typeof(FinancialsContext))]
    partial class FinancialsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("Financials.Data.Asset", b =>
                {
                    b.Property<int>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("AssociatedDebts")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("AssociatedIncomes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("AssociatedInsurances")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("AssociatedInvestments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("AssociatedSavings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<int>("ContactId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExpenseNotes")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HOAFees")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("HOAFeesDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("HouseholdId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("InsCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("InsCostDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OtherCosts")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("OtherCostsDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnershipDetail")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OwnershipPct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("OwnershipPctDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PurchPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PurchPriceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportDesc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportHoverNote")
                        .HasColumnType("TEXT");

                    b.Property<int>("SpouseId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Taxes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("TaxesDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Timeframe")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ValueDate")
                        .HasColumnType("TEXT");

                    b.HasKey("AssetId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("Financials.Data.Classes.Saving", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("AssociatedAssets")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("AssociatedDebts")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("AssociatedIncomes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("AssociatedInsurances")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("AssociatedInvestments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ContactId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportDesc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportHoverNote")
                        .HasColumnType("TEXT");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ValueDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Savings");
                });

            modelBuilder.Entity("Financials.Data.Debt", b =>
                {
                    b.Property<int>("DebtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AdjustableRate")
                        .HasColumnType("decimal(18,2)");

                    b.PrimitiveCollection<string>("AssociatedAssets")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("AssociatedIncomes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("AssociatedInsurances")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("AssociatedInvestments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("AssociatedSavings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("BalanceDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("BorrowLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<int>("ContactId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("EscrowPayment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("EscrowPaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FutureAdjustDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FutureAdjustRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FuturePaymentMade")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("HasBalloonPayment")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HouseholdId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InterestRate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsInterestOnly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LenderName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LenderPhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("LenderPhoneExt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoanNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoanRepresentative")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MinimumPayment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OriginalLoanAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("OriginalLoanDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PaymentMade")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RateTiedTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportDesc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportHoverNote")
                        .HasColumnType("TEXT");

                    b.Property<int>("SpouseId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Spread")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Term")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Timeframe")
                        .HasColumnType("TEXT");

                    b.HasKey("DebtId");

                    b.ToTable("Debts");
                });

            modelBuilder.Entity("Financials.Data.Investment", b =>
                {
                    b.Property<int>("InvestmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountType")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AfterTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AnnualReturn")
                        .HasColumnType("decimal(18,2)");

                    b.PrimitiveCollection<string>("AssociatedAssets")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("AssociatedDebts")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("AssociatedIncomes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("AssociatedInsurances")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("AssociatedSavings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<int>("ContactId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("CostBasis")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CurrentValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DividendYield")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ExpenseRatio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Firm")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("HouseholdId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Institution")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("InterestRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("InvestmentType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("MaturityDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Outside")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Owner")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PreTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PurchasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReportDesc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportHoverNote")
                        .HasColumnType("TEXT");

                    b.Property<string>("RiskLevel")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Roth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SharePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Shares")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpouseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TaxPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Timeframe")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("UnrealizedGainLoss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ValueDate")
                        .HasColumnType("TEXT");

                    b.HasKey("InvestmentId");

                    b.ToTable("Investments");
                });
#pragma warning restore 612, 618
        }
    }
}
